server:
  port: 8888

spring:
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/fintech-java
  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        sql: warn

kudago-api:
  cities-uri: https://kudago.com/public-api/v1.4/locations/
  categories-uri: https://kudago.com/public-api/v1.4/place-categories/
  events-uri: https://kudago.com/public-api/v1.4/events/
  executors-config:
    data-initializer-thread-amount: 10
    data-scheduler-duration: 600s
    event-data-getter-thread-amount: 10
  event-rate-limit: 10

currency-api:
  convert-currency-uri: http://localhost:8080/api/v1/currencies/convert

jwt:
  secret: 0KDQsNC3INC00LLQsCDQstC+0YHQtdC80YzRgdC+0YIg0LTQstCwINC00Y/RgtC70LAg0YHQuNC00LXQu9C4INC90LAg0YHQvNC+0YLRgNC10LvQuC4g0JLRh9C10YDQsCDRg9GC0YDQvtC8INC4INGPINC80Ysg0YHQtdCz0L7QtNC90Y8g0LLQuNC00LjQvCDQstGB0LXRhSDQstC+0LrRgNGD0LMu